# configuration for https://travis-ci.org/bitcoinj/bitcoinj
sudo: false
language: java
jdk: oraclejdk8
install: true
# remove default
  - sudo apt-get -qq update
  - sudo apt-get install -y protobuf-compiler
script:
  - gradle -q clean install
  - jdk_switcher use openjdk6
  - cd orchid
  - gradle -q clean build
  - cd core
  - gradle -q clean build

notifications:
  irc:
    channels: "irc.freenode.net#wagerrj"
    skip_join: true
